---

- hosts: localhost
  connection: local
  become: true
  pre_tasks: 

    - name: Update repository index
      package:
        update_cache: yes
      changed_when: false

  tasks:
    - include_tasks: tasks/users.yaml
    - include_tasks: tasks/cron.yaml
    - include_tasks: tasks/packages.yaml
